name: Create New Repository

on:
  repository_dispatch:
    types: [create-repo]

jobs:
  create-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Create a new repository using GitHub API
      id: create_repo
      run: |
        ORG_NAME="squarebtech"
        TEMPLATE_OWNER="squarebtech"  # Typically the same as ORG_NAME
        TEMPLATE_REPO="repo-template"
        REPO_NAME=${{ github.event.client_payload.repo_name }}
        DESCRIPTION="${{ github.event.client_payload.description }}"
        TOKEN=${{ secrets.SBT_TOKEN }}
        
        curl -H "Authorization: token $TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/$TEMPLATE_OWNER/$TEMPLATE_REPO/generate\
             -d '{
               "owner": "'"$ORG_NAME"'",
               "name": "'"$REPO_NAME"'",
               "description": "'"$DESCRIPTION"'",
               "private": false,
               "include_all_branches": true
             }'

         # echo "Response: $RESPONSE"

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Check if repository creation was successful
      id: check_repo
      run: |
        REPO_NAME=${{ github.event.client_payload.repo_name }}
        ORG_NAME="squarebtech"
        TOKEN=${{ secrets.SBT_TOKEN }}
        
        REPO_CHECK=$(curl -H "Authorization: token $TOKEN" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://api.github.com/repos/$ORG_NAME/$REPO_NAME)
        
        echo "Repository Check: $REPO_CHECK"

    - name: Set branch protection rules
      # if: steps.check_repo.outputs.success == 'true'
      run: |
        ORG_NAME="squarebtech"
        REPO_NAME=${{ github.event.client_payload.repo_name }}
        TOKEN=${{ secrets.SBT_TOKEN }}
        
        curl -H "Authorization: token $TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             -X PUT \
             https://api.github.com/repos/$ORG_NAME/$REPO_NAME/branches/main/protection \
             -d '{
               "required_status_checks": {
                 "strict": true,
                 "contexts": []
               },
               "enforce_admins": true,
               "required_pull_request_reviews": {
                 "required_approving_review_count":1,
                 "dismiss_stale_reviews": true,
                 "require_code_owner_reviews": true,
                 "require_last_push_approval": true
               },
               "require_conversation_resolution: true,
               "allow_force_pushes": false,
               "allow_deletions": false,
               "restrictions": null
             }'


    # - name: Add default labels
    #   run: |
    #     ORG_NAME="YOUR_ORG_NAME"
    #     REPO_NAME=new-repo-${{ github.event.client_payload.repo_name }}
    #     TOKEN=${{ secrets.GITHUB_TOKEN }}
        
    #     LABELS=("bug" "documentation" "enhancement" "question")
    #     for LABEL in "${LABELS[@]}"; do
    #       curl -H "Authorization: token $TOKEN" \
    #            -H "Accept: application/vnd.github.v3+json" \
    #            https://api.github.com/repos/$ORG_NAME/$REPO_NAME/labels \
    #            -d '{
    #              "name": "'"$LABEL"'",
    #              "color": "f29513"
    #            }'
    #     done
